Fix frf 215 removed broken aria controls in navigation menu
PA-NIHR-CRN/frf-web pull request #202
Opened 2023-11-13 12:55 UTC by ThomasJackSmolen

Removed the broken aria-controls label in Header.tsx to remove this error from all pages.
Removed the test for this in the Home.spec.tsx file.

2023-11-13 15:58 UTC, Jaffacakes82 commented
@kevinofficer I'm not sure if this PR is merging into the right branch? Please can you check.

2023-11-14 09:48 UTC, kevinofficer commented
@Jaffacakes82 yep all good, I've got the apprentices merging into temp once approved I'm merging them into main

2023-11-14 17:28 UTC, Jaffacakes82 commented
So can this be closed without merging?

2023-11-15 10:36 UTC, kevinofficer requested changes

2023-11-21 13:09 UTC, kevinofficer commented on src/mocks/homepage/success.json
> -        "metaTitle": "Homepage Title",
Add this title back into the file, and run the unit tests. 
You can run the unit tests with the command line: npm run test

2023-11-21 13:21 UTC, kevinofficer approved these changes

2023-11-21 13:34 UTC, merged